title: chenleifan's Homepage
page-top-title: chenleifan
top-section-bg-text: Be what you wanna be
home-subtitle: chenleifan&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; chenleifan 2023-2025. All Rights Reserved.'
